package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/stausee1337/qrpc/analysis"
)

type Options struct {
	OutDir 		string
	PackageName string
}

func CodegenFromAnalysis(analysis analysis.AnalysisResult, options Options) error {
	t, err := loadCGTemplates(analysis)
	if err != nil {
		return err
	}

	if err = os.MkdirAll(options.OutDir, os.ModePerm); err != nil {
		return err
	}

	if err = options.generateAndEmit(&t, "generated"); err != nil {
		return err
	}

	if err = options.generateAndEmit(&t, "models"); err != nil {
		return err
	}

	return nil
}

func (o *Options) generateAndEmit(t *templates, name string) error {
	source, err := t.generateCode(name)
	if err != nil {
		return err
	}

	source = append(o.getFileHeader(&t.analysis, name), source...)

	source, err = format.Source(source)
	if err != nil {
		return err
	}

	filename := fmt.Sprintf("%v.go", name)
	file, err := os.Create(path.Join(o.OutDir, filename))
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.Write(source)
	if err != nil {
		return err
	}

	return nil
}

func (o *Options) getFileHeader(analysis *analysis.AnalysisResult, name string) []byte {
	head := fmt.Sprintf(
`// THIS FILE WAS GENERATED BY qrpc - DO NOT EDIT!
package %v

`, o.PackageName)

	var imports []string
	switch name {
	case "generated":
		addImports(
			&imports,
			"context",
			"net/http",
			"github.com/stausee1337/qrpc/qrpc",
		)

		if serviceRequiresUUID(analysis.Services) {
			addImports(&imports, "github.com/google/uuid")
		}
	case "models":
		if udTypeRequiresUUID(analysis.Types) {
			addImports(&imports, "github.com/google/uuid")
		}
	default:
		panic("invalid key in model")
	}

	return []byte(head + fmt.Sprintf("import (%v)", strings.Join(imports, "\n")))
}

func addImports(imports *[]string, paths...string) {
	for _, path := range paths {
		newImport := fmt.Sprintf("%q", path)
		*imports = append(*imports, newImport) 
	}
}

func serviceRequiresUUID(services []analysis.Service) bool {
	for _, service := range services {
		for _, operation := range service.Operations {
			for _, ty := range operation.InputTypes {
				if checkUUIDDeeply(ty.Type) {
					return true;
				}
			}
			if checkUUIDDeeply(operation.ResultType) {
				return true;
			}
		}
	}

	return false
}

func udTypeRequiresUUID(udts []analysis.UserDefinedType) bool {
	for _, udt := range udts {
		record, ok := udt.(*analysis.RecordType)
		if !ok {
			continue
		}
		for _, ty := range record.Fields {
			if checkUUIDDeeply(ty.Type) {
				return true;
			}
		}
	}

	return false
}

func checkUUIDDeeply(ty analysis.Type) bool {
	switch v := ty.(type) {
	case *analysis.UUIDType:
		return true;
	case *analysis.OptionalType:
		return checkUUIDDeeply(v.Type);
	case *analysis.ArrayType:
		return checkUUIDDeeply(v.Type);
	case *analysis.UnionType:
		return slices.ContainsFunc(v.Types, checkUUIDDeeply);
	default:
		return false
	}
}

